It should answer:
1. What assets are in the portfolio?
2. What prices did we obtain?
3. Are the prices clean?
4. How do we handle missing observations?
5. What are the daily returns?
6. Are the resulting returns reasonable?

In [6]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parents[1]
sys.path.append(str(PROJECT_ROOT))

from project_01_market_risk_engine.src.data import download_prices

Define the initial universe

In [7]:
TICKERS = [
    "SPY",
    "QQQ",
    "IWM",
    "TLT",
    "GLD"
]

START_DATE = "2015-01-01"
END_DATE = "2026-01-01"

In [8]:
prices = download_prices(
    tickers=TICKERS,
    start=START_DATE,
    end=END_DATE
)

prices.head()

[*********************100%***********************]  5 of 5 completed

Ticker             GLD         IWM        QQQ         SPY        TLT
Date
2015-01-02  114.080002  102.276001  94.462730  169.267487  91.566475
2015-01-05  115.800003  100.908638  93.077065  166.210587  93.004799
2015-01-06  117.120003   99.162926  91.829056  164.645081  94.680511
2015-01-07  116.430000  100.384079  93.012848  166.696793  94.493584
2015-01-08  115.940002  102.086823  94.793060  169.654785  93.242142

In [10]:
prices.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 2766 entries, 2015-01-02 to 2025-12-31
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   GLD     2766 non-null   float64
 1   IWM     2766 non-null   float64
 2   QQQ     2766 non-null   float64
 3   SPY     2766 non-null   float64
 4   TLT     2766 non-null   float64
dtypes: float64(5)
memory usage: 129.7 KB

In [11]:
prices.describe()

Ticker          GLD          IWM          QQQ          SPY          TLT
count   2766.000000  2766.000000  2766.000000  2766.000000  2766.000000
mean     165.752133   158.439438   263.978955   335.312008    98.834372
std       60.066126    41.414078   143.848931   139.639486    15.526647
min      100.500000    82.705093    89.282806   153.779739    72.833443
25%      120.902502   124.267094   137.689312   217.810299    87.941200
50%      159.375000   151.497566   241.022705   298.388916    94.267574
75%      180.630001   195.262970   358.547218   419.840744   106.483677
max      416.739990   255.207123   632.796753   685.029480   141.016525

In [12]:
prices.isna().sum()

Ticker
GLD    0
IWM    0
QQQ    0
SPY    0
TLT    0
dtype: int64